#!/bin/bash

#launcher

#Manual = 0

#Exit code
INVALID_NUMBER_OF_ARGUMENTS=1
INVALID_ARGUMENTS=2

root_path=""

#pwd

echo -e "\nGIT MAISON LO14\n"

#number of arguments control
if [ $# -ne 4 ]
then
	echo -e "invalid number of argument\n You need to use $0 path_treeA path_treeB -option(a/m) path_log"
	exit $INVALID_NUMBER_OF_ARGUMENTS
fi
#$1 control
if [[ ! -d $1 ]]
then
	echo -e "$1 is not a directory"
	exit $INVALID_ARGUMENTS
fi
#$2 control
if [[ ! -d $2 ]]
then
	echo -e "$2 is not a directory"
        exit $INVALID_ARGUMENTS
fi

if [[ "$3" == "-m" ]]
then
	touch $4
	if [[ ! -f $4 ]]
	then
		echo "$4 is not a file, you can't use it for saving a log"
		exit $INVALID_ARGUMENTS
	fi
elif [[ "$3" == "-a" ]]
then
	if [ -f $4 ]
	then
		head=$(head -n1 $4)
		if [[ "$head" != "synchronizer_log" ]]
			then
			echo "$4 is not a log file for this synchronizer"
			exit $INVALID_ARGUMENTS
		fi
	else
		"$4 is not a log file for this synchronizer"
		exit $INVALID_ARGUMENTS
	fi
else
	echo -e "$3 is not an option for this synchronizer \ntry -a or -m "
        exit $INVALID_ARGUMENTS
fi

#current_log initiation
touch /tmp/synchronizer_current_log
if [[ "$3" == "-a" ]]
then
	echo $4 > /tmp/synchronizer_current_log
fi

${root_path}bin/main_explorer $1 $2

path_size_to_delete=$(echo $1 | wc -m) #AJOUTER +1
path_size_to_delete=$((path_size_to_delete+=1))

echo "synchronizer_log" > $4
${root_path}bin/log_generator $1 path_size_to_delete $4 

